site_name: SU VR Course

theme:
    name: cinder
    custom_dir: cinder-theme-ext

extra_css:
    - css/extra.css

nav:
    # - Home: index.md
    # - TP:
    #   - TP1: tp-audio-spat.md
    #   - TP2: tp-audio-spat.md
    - Lectures: lectures.md
    - Tutorials: tutorials.md
    - Gallery: gallery.md


# repo_url: "https://forge-2.ircam.fr/davipoir/sorbonne-vr-ue-website"

extra:
  collapse_toc: true
  toc_depth: 1
  include_search: false
