site_name: Sorbonne - Virtual Reality UE

theme:
    name: material
    palette:
        primary: indigo
    # name: cinder
    # custom_dir: cinder-theme-ext

extra_css:
    - css/extra.css

nav:
    - Home: index.md
    # - Lectures: lectures.md
    - Tutorials: tutorials.md
    # - Gallery: gallery.md

markdown_extensions:
    - attr_list

# repo_url: "https://forge-2.ircam.fr/davipoir/sorbonne-vr-ue-website"

# extra:
  # collapse_toc: true
  # toc_depth: 1
  # include_search: false
